const schoolCodes = [
  {
    SchoolName: "Ananda College Colombo 10",
    Team: "A",
    SchoolCode: "ACC-A",
  },
  {
    SchoolName: "Ananda College Colombo 10",
    Team: "B",
    SchoolCode: "ACC-B",
  },
  {
    SchoolName: "Ananda College Colombo 10",
    Team: "C",
    SchoolCode: "ACC-C",
  },
  {
    SchoolName: "Ananda Maiththreya Central College, Balangoda",
    Team: "A",
    SchoolCode: "AMB-A",
  },
  {
    SchoolName: "Ananda Maiththreya Central College, Balangoda",
    Team: "B",
    SchoolCode: "AMB-B",
  },
  {
    SchoolName: "Ananda Maiththreya Central College, Balangoda",
    Team: "C",
    SchoolCode: "AMB-C",
  },
  {
    SchoolName: "Anula Devi Girls' College",
    Team: "A",
    SchoolCode: "ADG-A",
  },
  {
    SchoolName: "Bandaranayake Central College, Veyangoda",
    Team: "A",
    SchoolCode: "BCV-A",
  },
  {
    SchoolName: "Bandaranayake Central College, Veyangoda",
    Team: "B",
    SchoolCode: "BCV-B",
  },
  {
    SchoolName: "Bandaranayake Central College, Veyangoda",
    Team: "C",
    SchoolCode: "BCV-C",
  },
  {
    SchoolName: "Bandaranayake College, Gampaha",
    Team: "A",
    SchoolCode: "BCG-A",
  },
  {
    SchoolName: "Bandaranayake College, Gampaha",
    Team: "B",
    SchoolCode: "BCG-B",
  },
  {
    SchoolName: "De Mazenod College",
    Team: "A",
    SchoolCode: "DMK-A",
  },
  {
    SchoolName: "De Mazenod College",
    Team: "B",
    SchoolCode: "DMK-B",
  },
  {
    SchoolName: "De Mazenod College",
    Team: "C",
    SchoolCode: "DMK-C",
  },
  {
    SchoolName: "Defence Services College, Colombo 02",
    Team: "A",
    SchoolCode: "DSC-A",
  },
  {
    SchoolName: "Defence Services College, Colombo 02",
    Team: "B",
    SchoolCode: "DSC-B",
  },
  {
    SchoolName: "Defence Services College, Colombo 02",
    Team: "C",
    SchoolCode: "DSC-C",
  },
  {
    SchoolName: "Dharmaraja College, Kandy",
    Team: "A",
    SchoolCode: "DCK-A",
  },
  {
    SchoolName: "Dharmaraja College, Kandy",
    Team: "B",
    SchoolCode: "DCK-B",
  },
  {
    SchoolName: "Devi Balika Vidyalaya, Colombo 08",
    Team: "A",
    SchoolCode: "DBC-A",
  },
  {
    SchoolName: "Ferguson High School, Ratnapura",
    Team: "A",
    SchoolCode: "FHR-A",
  },
  {
    SchoolName: "G/ Christ Church Boys College",
    Team: "A",
    SchoolCode: "CBG-A",
  },
  {
    SchoolName: "G/ Christ Church Girls College",
    Team: "A",
    SchoolCode: "CGG-A",
  },
  {
    SchoolName: "Girls High School Kandy",
    Team: "A",
    SchoolCode: "GHK-A",
  },
  {
    SchoolName: "Girls High School Kandy",
    Team: "B",
    SchoolCode: "GHK-B",
  },
  {
    SchoolName: "Girls High School Kandy",
    Team: "C",
    SchoolCode: "GHK-C",
  },
  {
    SchoolName: "H/Sri Lanka Singapore Friendship College",
    Team: "A",
    SchoolCode: "SFH-A",
  },
  {
    SchoolName: "H/Sri Lanka Singapore Friendship College",
    Team: "B",
    SchoolCode: "SFH-B",
  },
  {
    SchoolName: "Isipathana College",
    Team: "A",
    SchoolCode: "ICC-A",
  },
  {
    SchoolName: "Kg/St.Josephs Balika M.V.",
    Team: "A",
    SchoolCode: "JBK-A",
  },
  {
    SchoolName: "Kg/St.Josephs Balika M.V.",
    Team: "B",
    SchoolCode: "JBK-B",
  },
  {
    SchoolName: "Kingswood College Kandy",
    Team: "A",
    SchoolCode: "KCK-A",
  },
  {
    SchoolName: "Kingswood College Kandy",
    Team: "B",
    SchoolCode: "KCK-B",
  },
  {
    SchoolName: "Mahamaya Girls' College Kandy",
    Team: "A",
    SchoolCode: "MGK-A",
  },
  {
    SchoolName: "Mahamaya Girls' College Kandy",
    Team: "B",
    SchoolCode: "MGK-B",
  },
  {
    SchoolName: "Mahamaya Girls' College Kandy",
    Team: "C",
    SchoolCode: "MGK-C",
  },
  {
    SchoolName: "Mahinda College Galle",
    Team: "A",
    SchoolCode: "MCG-A",
  },
  {
    SchoolName: "Mahinda Rajapaksha College-Homagama",
    Team: "A",
    SchoolCode: "MRH-A",
  },
  {
    SchoolName: "Nalanda College, Colombo",
    Team: "A",
    SchoolCode: "NCC-A",
  },
  {
    SchoolName: "Nalanda College, Colombo",
    Team: "B",
    SchoolCode: "NCC-B",
  },
  {
    SchoolName: "Nalanda College, Colombo",
    Team: "C",
    SchoolCode: "NCC-C",
  },
  {
    SchoolName: "Piliyandal Central College",
    Team: "A",
    SchoolCode: "PLCC-A",
  },
  {
    SchoolName: "Pinnawala Central College",
    Team: "A",
    SchoolCode: "PNCC-A",
  },
  {
    SchoolName: "Pushpadana Girls' college, kandy",
    Team: "A",
    SchoolCode: "PGK-A",
  },
  {
    SchoolName: "Rahula College Matara",
    Team: "A",
    SchoolCode: "RCM-A",
  },
  {
    SchoolName: "Rahula College Matara",
    Team: "B",
    SchoolCode: "RCM-B",
  },
  {
    SchoolName: "Rahula College Matara",
    Team: "C",
    SchoolCode: "RCM-C",
  },
  {
    SchoolName: "Rathnavali Balika Vidyalaya Gampaha",
    Team: "A",
    SchoolCode: "RBG-A",
  },
  {
    SchoolName: "Royal College Colombo",
    Team: "A",
    SchoolCode: "RCC-A",
  },
  {
    SchoolName: "Royal College Colombo",
    Team: "B",
    SchoolCode: "RCC-B",
  },
  {
    SchoolName: "Sangamitta Balika Vidyalaya",
    Team: "A",
    SchoolCode: "SBG-A",
  },
  {
    SchoolName: "Sangamitta Balika Vidyalaya",
    Team: "B",
    SchoolCode: "SBG-B",
  },
  {
    SchoolName: "Sirimavo Bandaranaike Vidyalaya",
    Team: "A",
    SchoolCode: "SBC-A",
  },
  {
    SchoolName: "Sivali Central College",
    Team: "A",
    SchoolCode: "SCC-A",
  },
  {
    SchoolName: "Southlands College Galle",
    Team: "A",
    SchoolCode: "SCG-A",
  },
  {
    SchoolName: "St.Aloysius' College, Galle",
    Team: "A",
    SchoolCode: "SAG-A",
  },
  {
    SchoolName: "St.Servatius’ College",
    Team: "A",
    SchoolCode: "SSM-A",
  },
  {
    SchoolName: "St.Sylvester's College",
    Team: "A",
    SchoolCode: "SSK-A",
  },
  {
    SchoolName: "St.Sylvester's College",
    Team: "B",
    SchoolCode: "SSK-B",
  },
  {
    SchoolName: "Vidyaloka College Galle",
    Team: "A",
    SchoolCode: "VCG-A",
  },
  {
    SchoolName: "Vidyarathna University College Horana",
    Team: "A",
    SchoolCode: "VUC-A",
  },
  {
    SchoolName: "Viharamahadevi Balika Vidyalaya Kiribathgoda",
    Team: "A",
    SchoolCode: "VBV-A",
  },
  {
    SchoolName: "Visakha Vidyalaya",
    Team: "A",
    SchoolCode: "VVC-A",
  },
  {
    SchoolName: "Zahira College Colombo",
    Team: "A",
    SchoolCode: "ZCC-A",
  },
];

const results = [
  {
    Place: "1",
    SchoolName: "Royal College Colombo",
    Team: "A",
    TeamCode: "RCC-A",
    Percentage: 78.55,
  },
  {
    Place: "2",
    SchoolName: "Ananda College Colombo 10",
    Team: "A",
    TeamCode: "ACC-A",
    Percentage: 71.29,
  },
  {
    Place: "3",
    SchoolName: "Rahula College Matara",
    Team: "A",
    TeamCode: "RCM-A",
    Percentage: 67.58,
  },
  {
    Place: "4",
    SchoolName: "Royal College Colombo",
    Team: "B",
    TeamCode: "RCC-B",
    Percentage: 64.84,
  },
  {
    Place: "5",
    SchoolName: "Nalanda College, Colombo",
    Team: "B",
    TeamCode: "NCC-B",
    Percentage: 64.68,
  },
  {
    Place: "6",
    SchoolName: "Isipathana College",
    Team: "A",
    TeamCode: "ICC-A",
    Percentage: 63.55,
  },
  {
    Place: "7",
    SchoolName: "De Mazenod College",
    Team: "A",
    TeamCode: "DMK-A",
    Percentage: 61.94,
  },
  {
    Place: "8",
    SchoolName: "Mahamaya Girls' College Kandy",
    Team: "A",
    TeamCode: "MGK-A",
    Percentage: 61.61,
  },
  {
    Place: "9",
    SchoolName: "Mahinda Rajapaksha College-Homagama",
    Team: "A",
    TeamCode: "MRH-A",
    Percentage: 57.42,
  },
  {
    Place: "10",
    SchoolName: "Rahula College Matara",
    Team: "B",
    TeamCode: "RCM-B",
    Percentage: 56.29,
  },
  {
    Place: "11",
    SchoolName: "Sivali Central College",
    Team: "A",
    TeamCode: "SCC-A",
    Percentage: 55.0,
  },
  {
    Place: "12",
    SchoolName: "Kingswood College Kandy",
    Team: "B",
    TeamCode: "KCK-B",
    Percentage: 53.87,
  },
  {
    Place: "13",
    SchoolName: "Bandaranayake College, Gampaha",
    Team: "A",
    TeamCode: "BCG-A",
    Percentage: 52.58,
  },
  {
    Place: "14",
    SchoolName: "Nalanda College, Colombo",
    Team: "A",
    TeamCode: "NCC-A",
    Percentage: 52.1,
  },
  {
    Place: "15",
    SchoolName: "Bandaranayake Central College, Veyangoda",
    Team: "A",
    TeamCode: "BCV-A",
    Percentage: 51.61,
  },
  {
    Place: "16",
    SchoolName: "Dharmaraja College, Kandy",
    Team: "A",
    TeamCode: "DCK-A",
    Percentage: 51.45,
  },
  {
    Place: "17",
    SchoolName: "Ananda College Colombo 10",
    Team: "B",
    TeamCode: "ACC-B",
    Percentage: 50.81,
  },
  {
    Place: "18",
    SchoolName: "Dharmaraja College, Kandy",
    Team: "B",
    TeamCode: "DCK-B",
    Percentage: 49.35,
  },
  {
    Place: "19",
    SchoolName: "Defence Services College, Colombo 02",
    Team: "A",
    TeamCode: "DSC-A",
    Percentage: 49.03,
  },
  {
    Place: "20",
    SchoolName: "Ananda College Colombo 10",
    Team: "C",
    TeamCode: "ACC-C",
    Percentage: 48.71,
  },
  {
    Place: "21",
    SchoolName: "Bandaranayake College, Gampaha",
    Team: "B",
    TeamCode: "BCG-B",
    Percentage: 45.97,
  },
  {
    Place: "22",
    SchoolName: "H/Sri Lanka Singapore Friendship College",
    Team: "A",
    TeamCode: "SFH-A",
    Percentage: 45.0,
  },
  {
    Place: "23",
    SchoolName: "Girls High School Kandy",
    Team: "B",
    TeamCode: "GHK-B",
    Percentage: 43.71,
  },
  {
    Place: "24",
    SchoolName: "Sirimavo Bandaranaike Vidyalaya",
    Team: "A",
    TeamCode: "SBC-A",
    Percentage: 43.23,
  },
  {
    Place: "25",
    SchoolName: "Sangamitta Balika Vidyalaya",
    Team: "B",
    TeamCode: "SBG-B",
    Percentage: 43.06,
  },
  {
    Place: "26",
    SchoolName: "Mahamaya Girls' College Kandy",
    Team: "B",
    TeamCode: "MGK-B",
    Percentage: 42.74,
  },
  {
    Place: "27",
    SchoolName: "Bandaranayake Central College, Veyangoda",
    Team: "B",
    TeamCode: "BCV-B",
    Percentage: 40.48,
  },
  {
    Place: "28",
    SchoolName: "Pushpadana Girls' college, Kandy",
    Team: "A",
    TeamCode: "PGK-A",
    Percentage: 39.35,
  },
  {
    Place: "29",
    SchoolName: "Visakha Vidyalaya",
    Team: "A",
    TeamCode: "VVC-A",
    Percentage: 38.71,
  },
  {
    Place: "30",
    SchoolName: "Nalanda College, Colombo",
    Team: "C",
    TeamCode: "NCC-C",
    Percentage: 38.55,
  },
  {
    Place: "31",
    SchoolName: "Ferguson High School, Ratnapura",
    Team: "A",
    TeamCode: "FHR-A",
    Percentage: 35.65,
  },
  {
    Place: "32",
    SchoolName: "Sangamitta Balika Vidyalaya",
    Team: "A",
    TeamCode: "SBG-A",
    Percentage: 34.84,
  },
  {
    Place: "33",
    SchoolName: "Girls High School Kandy",
    Team: "C",
    TeamCode: "GHK-C",
    Percentage: 34.52,
  },
  {
    Place: "34",
    SchoolName: "Rahula College Matara",
    Team: "C",
    TeamCode: "RCM-C",
    Percentage: 34.19,
  },
  {
    Place: "35",
    SchoolName: "St.Sylvester's College",
    Team: "A",
    TeamCode: "SSK-A",
    Percentage: 34.03,
  },
  {
    Place: "36",
    SchoolName: "St.Servatius’ College",
    Team: "A",
    TeamCode: "SSM-A",
    Percentage: 33.39,
  },
  {
    Place: "37",
    SchoolName: "Mahamaya Girls' College Kandy",
    Team: "C",
    TeamCode: "MGK-C",
    Percentage: 33.06,
  },
  {
    Place: "38",
    SchoolName: "Piliyandal Central College",
    Team: "A",
    TeamCode: "PLCC-A",
    Percentage: 32.74,
  },
  {
    Place: "39",
    SchoolName: "Mahinda College Galle",
    Team: "A",
    TeamCode: "MCG-A",
    Percentage: 32.58,
  },
  {
    Place: "40",
    SchoolName: "Rathnavali Balika Vidyalaya Gampaha",
    Team: "A",
    TeamCode: "RBG-A",
    Percentage: 30.48,
  },
  {
    Place: "41",
    SchoolName: "De Mazenod College",
    Team: "B",
    TeamCode: "DMK-B",
    Percentage: 30.48,
  },
  {
    Place: "42",
    SchoolName: "G/ Christ Church Boys College",
    Team: "A",
    TeamCode: "CBG-A",
    Percentage: 29.84,
  },
  {
    Place: "43",
    SchoolName: "Zahira College Colombo",
    Team: "A",
    TeamCode: "ZCC-A",
    Percentage: 27.74,
  },
  {
    Place: "44",
    SchoolName: "Girls High School Kandy",
    Team: "A",
    TeamCode: "GHK-A",
    Percentage: 27.42,
  },
  {
    Place: "45",
    SchoolName: "Ananda Maiththreya Central College, Balangoda",
    Team: "A",
    TeamCode: "AMB-A",
    Percentage: 25.97,
  },
  {
    Place: "46",
    SchoolName: "Defence Services College, Colombo 02",
    Team: "B",
    TeamCode: "DSC-B",
    Percentage: 24.19,
  },
  {
    Place: "47",
    SchoolName: "St.Aloysius' College, Galle",
    Team: "A",
    TeamCode: "SAG-A",
    Percentage: 23.39,
  },
  {
    Place: "48",
    SchoolName: "Devi Balika Vidyalaya, Colombo 08",
    Team: "A",
    TeamCode: "DBC-A",
    Percentage: 20.65,
  },
  {
    Place: "49",
    SchoolName: "Vidyaloka College Galle",
    Team: "A",
    TeamCode: "VCG-A",
    Percentage: 19.84,
  },
  {
    Place: "50",
    SchoolName: "Kingswood College Kandy",
    Team: "A",
    TeamCode: "KCK-A",
    Percentage: 19.52,
  },
  {
    Place: "51",
    SchoolName: "Vidyarathna University College Horana",
    Team: "A",
    TeamCode: "VUC-A",
    Percentage: 19.52,
  },
  {
    Place: "52",
    SchoolName: "Southlands College Galle",
    Team: "A",
    TeamCode: "SCG-A",
    Percentage: 19.35,
  },
  {
    Place: "53",
    SchoolName: "Bandaranayake Central College, Veyangoda",
    Team: "C",
    TeamCode: "BCV-C",
    Percentage: 16.13,
  },
  {
    Place: "54",
    SchoolName: "Ananda Maiththreya Central College, Balangoda",
    Team: "B",
    TeamCode: "AMB-B",
    Percentage: 15.97,
  },
  {
    Place: "55",
    SchoolName: "Kg/St.Josephs Balika M.V.",
    Team: "B",
    TeamCode: "JBK-B",
    Percentage: 15.81,
  },
  {
    Place: "56",
    SchoolName: "Defence Services College, Colombo 02",
    Team: "C",
    TeamCode: "DSC-C",
    Percentage: 14.03,
  },
  {
    Place: "57",
    SchoolName: "St.Sylvester's College",
    Team: "B",
    TeamCode: "SSK-B",
    Percentage: 11.45,
  },
  {
    Place: "58",
    SchoolName: "Kg/St.Josephs Balika M.V.",
    Team: "A",
    TeamCode: "JBK-A",
    Percentage: 10.97,
  },
  {
    Place: "59",
    SchoolName: "Ananda Maiththreya Central College, Balangoda",
    Team: "C",
    TeamCode: "AMB-C",
    Percentage: 10.16,
  },
  {
    Place: "60",
    SchoolName: "H/Sri Lanka Singapore Friendship College",
    Team: "B",
    TeamCode: "SFH-B",
    Percentage: 9.68,
  },
  {
    Place: "61",
    SchoolName: "G/ Christ Church Girls College",
    Team: "A",
    TeamCode: "CGG-A",
    Percentage: 9.52,
  },
  {
    Place: "62",
    SchoolName: "De Mazenod College",
    Team: "C",
    TeamCode: "DMK-C",
    Percentage: 7.42,
  },
  {
    Place: "63",
    SchoolName: "Anula Devi Girls' College",
    Team: "A",
    TeamCode: "ADG-A",
    Percentage: 0.0,
  },
  {
    Place: "63",
    SchoolName: "Pinnawala Central College",
    Team: "A",
    TeamCode: "PNCC-A",
    Percentage: 0.0,
  },
  {
    Place: "63",
    SchoolName: "Viharamahadevi Balika Vidyalaya Kiribathgoda",
    Team: "A",
    TeamCode: "VBV-A",
    Percentage: 0.0,
  },
];
